[package]
name = "mcc"
version = "0.1.0"
edition = "2024"

[dependencies]
ascii = "1.1.0"
thiserror = "2.0.12"
tinystr = "0.8.1"


[profile.release]
debug = true

[features]
    default = ["parse"]
    codegen = ["semantics"]
    semantics = ["parse"]
    parse = ["lex"]
    lex = []

